server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    instance:
      registryFetchIntervalSeconds: 30
      leaseRenewalIntervalInSeconds: 10
      leaseExpirationDurationInSeconds: 30