spring:
  application:
    name: routing-service
    
server:
  port: 1111
 
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: true
  routes:
    user:
      path: /registration/**
      service-id: registration-service
      retryable: true
    loan:
      path: /loan/**
      service-id: loan-service
      retryable: true
      
eureka:
  client:
    serviceUrl:
      defaultUrl: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    initial-instance-info-replication-interval-seconds: 1
    instance-info-replication-interval-seconds: 2
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000